### ISSUE TITLE
OK to mention in survey of Algorithmic Techniques for Book Publishing?

### ISSUE THREAD

**Issue by fredzannarbor** [tummychow/titlechaser#1]
Hi,

I would like to mention your work in a forthcoming book on the state of the art for algorithmic book publishing (Nimble Books 2023).  https://nimblebooks.com/Publishing_Information I also want to mention you in an upcoming event called "31 Days of AI for Book-Lovers" -- https://nimblebooks.com/Preface_--_31_Days_of_AI_for_Book-lovers

Can you please contact me at wfz@nimblebooks.com?

**Comment by tummychow** [comment]
sure, if you want to mention this project that's no problem at all - consider this my written acknowledgement that i'm okay with it. no guarantees of support or fitness for purpose, of course. this is just a random thing i threw together 5 years ago
